//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Final.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A) 的本地化字符串。
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连珠五子棋对战程序 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您犯规了！
        ///原因： 的本地化字符串。
        /// </summary>
        public static string BanInfo {
            get {
                return ResourceManager.GetString("BanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三三禁手 的本地化字符串。
        /// </summary>
        public static string BanT33 {
            get {
                return ResourceManager.GetString("BanT33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四四禁手 的本地化字符串。
        /// </summary>
        public static string BanT44 {
            get {
                return ResourceManager.GetString("BanT44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁点 的本地化字符串。
        /// </summary>
        public static string Bantip {
            get {
                return ResourceManager.GetString("Bantip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁手点提示 的本地化字符串。
        /// </summary>
        public static string BantipF {
            get {
                return ResourceManager.GetString("BantipF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁手警告 的本地化字符串。
        /// </summary>
        public static string BanTitle {
            get {
                return ResourceManager.GetString("BanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长连禁手 的本地化字符串。
        /// </summary>
        public static string BanTLong {
            get {
                return ResourceManager.GetString("BanTLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华文行楷 的本地化字符串。
        /// </summary>
        public static string ButtonFont {
            get {
                return ResourceManager.GetString("ButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        public static string ButtonFontSize {
            get {
                return ResourceManager.GetString("ButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对局配置 的本地化字符串。
        /// </summary>
        public static string ConfigGame {
            get {
                return ResourceManager.GetString("ConfigGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对局(&amp;P) 的本地化字符串。
        /// </summary>
        public static string GameMenu {
            get {
                return ResourceManager.GetString("GameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏结束 的本地化字符串。
        /// </summary>
        public static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局(&amp;G) 的本地化字符串。
        /// </summary>
        public static string GlobalMenu {
            get {
                return ResourceManager.GetString("GlobalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请求和棋！ 的本地化字符串。
        /// </summary>
        public static string PeaceAsk {
            get {
                return ResourceManager.GetString("PeaceAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和 的本地化字符串。
        /// </summary>
        public static string PeaceB {
            get {
                return ResourceManager.GetString("PeaceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求和棋 的本地化字符串。
        /// </summary>
        public static string PeaceBF {
            get {
                return ResourceManager.GetString("PeaceBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和棋提示 的本地化字符串。
        /// </summary>
        public static string PeaceInfo {
            get {
                return ResourceManager.GetString("PeaceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和棋！ 的本地化字符串。
        /// </summary>
        public static string PeaceNotice {
            get {
                return ResourceManager.GetString("PeaceNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双方同意和棋！ 的本地化字符串。
        /// </summary>
        public static string PeaceRequestNotice {
            get {
                return ResourceManager.GetString("PeaceRequestNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑方 的本地化字符串。
        /// </summary>
        public static string PlayerBlack {
            get {
                return ResourceManager.GetString("PlayerBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白方 的本地化字符串。
        /// </summary>
        public static string PlayerWhite {
            get {
                return ResourceManager.GetString("PlayerWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因 的本地化字符串。
        /// </summary>
        public static string ReasonNotice {
            get {
                return ResourceManager.GetString("ReasonNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放结束！ 的本地化字符串。
        /// </summary>
        public static string RecordEnd {
            get {
                return ResourceManager.GetString("RecordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棋谱错误 的本地化字符串。
        /// </summary>
        public static string RecordError {
            get {
                return ResourceManager.GetString("RecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已损坏！ 的本地化字符串。
        /// </summary>
        public static string RecordFileError {
            get {
                return ResourceManager.GetString("RecordFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取棋谱 的本地化字符串。
        /// </summary>
        public static string RecordGame {
            get {
                return ResourceManager.GetString("RecordGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停/恢复播放 的本地化字符串。
        /// </summary>
        public static string RecordPause {
            get {
                return ResourceManager.GetString("RecordPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棋谱已保存至 的本地化字符串。
        /// </summary>
        public static string RecordSaveNotice {
            get {
                return ResourceManager.GetString("RecordSaveNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中止播放 的本地化字符串。
        /// </summary>
        public static string RecordStop {
            get {
                return ResourceManager.GetString("RecordStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华文仿宋 的本地化字符串。
        /// </summary>
        public static string SmallButtonFont {
            get {
                return ResourceManager.GetString("SmallButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16 的本地化字符串。
        /// </summary>
        public static string SmallButtonFontSize {
            get {
                return ResourceManager.GetString("SmallButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始对局 的本地化字符串。
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认输 的本地化字符串。
        /// </summary>
        public static string Surrender {
            get {
                return ResourceManager.GetString("Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认输！ 的本地化字符串。
        /// </summary>
        public static string SurrenderNotice {
            get {
                return ResourceManager.GetString("SurrenderNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时！ 的本地化字符串。
        /// </summary>
        public static string TimeoutNotice {
            get {
                return ResourceManager.GetString("TimeoutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悔棋 的本地化字符串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求悔棋！ 的本地化字符串。
        /// </summary>
        public static string UndoAsk {
            get {
                return ResourceManager.GetString("UndoAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悔棋提示 的本地化字符串。
        /// </summary>
        public static string UndoInfo {
            get {
                return ResourceManager.GetString("UndoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已悔棋！ 的本地化字符串。
        /// </summary>
        public static string UndoNotice {
            get {
                return ResourceManager.GetString("UndoNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赢了！ 的本地化字符串。
        /// </summary>
        public static string WinNotice {
            get {
                return ResourceManager.GetString("WinNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连珠五子棋 的本地化字符串。
        /// </summary>
        public static string 连珠五子棋 {
            get {
                return ResourceManager.GetString("连珠五子棋", resourceCulture);
            }
        }
    }
}
